### ISSUE TITLE
add projects

### ISSUE THREAD

**Issue by viralRupani** [viralRupani/Portfolio2.0#1]
![image](https://user-images.githubusercontent.com/87006810/193437948-7707a8d6-7bd0-461e-a4a6-651dae6f5b72.png)

**Comment by yashkhandelwal2203** [comment]
Can you please explain what exactly i have to do?

**Comment by trishitchar** [comment]
Hey, I would like to work on this. Thanks!

**Comment by viralRupani** [comment]
We have to change code from HTML, CSS to react based I have updated  README.md
