### ISSUE TITLE
Typed not working

### ISSUE THREAD

**Issue by viralRupani** [viralRupani/Portfolio2.0#3]
![image](https://user-images.githubusercontent.com/87006810/193439363-13235332-c039-464f-ac4c-4114fdf3279d.png)

**Comment by Chitvan14** [comment]
Hi, I will be happy to solve this issue, please assign this to me.

**Comment by destroyer5067** [comment]
Hello, Can you assign this issue to me?

**Comment by Chitvan14** [comment]
@viralRupani  Should I push the code to master for #3?

**Comment by viralRupani** [comment]
yes you can push this to master directly

**Comment by Chitvan14** [comment]
Done, Please check.
