### ISSUE TITLE
responsive issue

### ISSUE THREAD

**Issue by viralRupani** [viralRupani/Portfolio2.0#7]
![image](https://user-images.githubusercontent.com/87006810/193443357-54ee9592-f183-40cb-9b6d-c95110ae6f15.png)
it should be centered at mobile size.

**Comment by Chitvan14** [comment]
Hi @viralRupani, assign this to me, according to the last issue I have resolved the text. Will resolve this issue too.

**Comment by viralRupani** [comment]
go ahead 😁
